### PR TITLE
Make tests run (they still fail)

### PR DESCRIPTION
**Pull request by Migelo**
I added a missed dependency and updated the checkout action to `v3`.

The tests still fail.

### CODE REVIEW

**Comment by ryantam626** [comment]
FWIW, I am in middle to a big refactor for the project (mostly due to the evolution of jupyterlab's plugin tooling), which should fix up the dev env and test suite properly.

**Comment by Migelo** [comment]
Ok, I will close this branch then.

**Comment by ryantam626** [comment]
@Migelo - just thought I would at least metnion that I am grateful of the fact you have spent time working on this :pray: :pray:

**Comment by Migelo** [comment]
I never assumed anything bad from your reply. I just found my pull request to be pointless if you're already on it. :) 
Thanks for the kind words!

**Pull request closed without merging**
