### PR TITLE
Format Menus and Buttons

### PR DESCRIPTION
**Pull request by mlucool**
This add the following:
1. Default formatter per file type
2. Right click context menu for formatting
3. A button to format the whole notebook

This refactors the python extension to handle formatting multiple cells as well.

### CODE REVIEW

**Comment by mazzma12** [comment]
Thank you for your work. Would it be possible to add a shortcut to trigger all cells formatting ?

**Comment by mlucool** [comment]
A button in the notebook toolbar has been added.

**Comment by ryantam626** [comment]
Ooo, thanks for this! I will try to get this merged some time soon.

**Comment by ryantam626** [comment]
Had another look and tested it just now, this is great!

Just a small nitpick
- The inability to pick more than one default formatters - I usually use black and isort together for normal python code;

Will merge and iterate on this later on - thank you so much again!

**Comment by mlucool** [comment]
Thanks for the quick review! Can this be released soon?

A few things I didn't get to were:
1. Picking an icon for the button (text is ugly right now)
2. Placement of format in the menu - it not precise

I like the idea of chaining formatters. We use [pyflyby ](https://github.com/pyflyby/pyflyby) and it would be nice to be able to say run pyflyby then black as my formatter on a cell by cell basis.

**Comment by ryantam626** [comment]
It should be included in latest release (v0.6.0) :grin:

**Comment by ryantam626** [comment]
Also, this pyflyby thing looks amazing!

**Pull request merged**
